{{- if .Values.schema }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-cm
data:
  schema.yaml: |-
    {{- toYaml .Values.schema | nindent 4 }}
{{- else }}
{{- fail "Schema not found." }}
{{- end }}
