---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-tmpl
  namespace: argo
spec:
  templates:
    - name: step
      inputs:
        parameters:
          - name: step
          - name: arguments
      container:
        image: '{{ .Values.workflow.image.repository }}:{{ .Values.workflow.image.tag }}'
        command: [ python ]
        args: [ -m, 'mar.workflow.{{`{{ inputs.parameters.step }}`}}', '{{`{{ inputs.parameters.arguments }}`}}' ]
        imagePullPolicy: IfNotPresent
