---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-tmpl
  namespace: argo
spec:
  templates:
    - name: transform-step
      inputs:
        parameters:
          - name: data
          - name: schema
          - name: target
      container:
        image: '{{ .Values.workflow.image.repository }}:{{ .Values.workflow.image.tag }}'
        command: [ python ]
        args:
          - -m
          - mar.workflow.transform
          - --data
          - '{{`{{ inputs.parameters.data }}`}}'
          - --schema
          - '{{`{{ inputs.parameters.schema }}`}}'
          - --target
          - '{{`{{ inputs.parameters.target }}`}}'
        imagePullPolicy: IfNotPresent
        env:
          - name: QDRANT_URL
            value: >
              {{ .Values.qdrant.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local
          - name: QDRANT_PORT
            value: 6333
