---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: transform-users
            templateRef: &template
              name: workflow-tmpl
              template: step
            arguments:
              parameters:
                - name: step
                  value: transform
                - name: arguments
                  value: >- 
                    --data foo
                    --schema bar
                    --target users