---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Release.Name }}
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: users
      - name: items
      - name: interactions
      - name: schema
  templates:
    - name: main
      dag:
        tasks:
          - name: transform-interactions
            templateRef:
              name: {{ .Release.Name }}-steps
              template: transform-step
            arguments:
              parameters:
                - name: data
                  value: '{{ `{{ inputs.parameters.interactions }}` }}'
                - name: schema
                  value: '{{ `{{ inputs.parameters.schema }}` }}'
            dependencies:
              - transform-users
              - transform-items
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Release.Name }}-steps
  namespace: argo
spec:
  templates:
    - name: transform-step
      inputs:
        parameters:
          - name: data
          - name: schema
      container:
        image: '{{ .Values.workflow.image.repository }}:{{ .Values.workflow.image.tag }}'
        command: [ python ]
        args:
          - -m
          - mar.workflow.transform
          - --data
          - '{{`{{ inputs.parameters.data }}`}}'
          - --schema
          - '{{`{{ inputs.parameters.schema }}`}}'
        imagePullPolicy: IfNotPresent
        env:
          - name: QDRANT_URL
            value: >
              {{ .Values.qdrant.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local
          - name: QDRANT_PORT
            value: '6333'
