---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: transform-users
            templateRef:
              name: workflow-tmpl
              template: transform-step
            arguments:
              parameters:
                - name: data
                  value: foo
                - name: schema
                  value: bar
                - name: target
                  value: baz
