---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Release.Name }}
  namespace: argo
spec:
  arguments: &workflow-arguments
    parameters:
      - name: interactions
  entrypoint: main
  templates:
    - name: main
      inputs:
        <<: *workflow-arguments
      dag:
        tasks:
          - name: transform-interactions
            templateRef:
              name: {{ .Release.Name }}-steps
              template: transform-step
            arguments:
              parameters:
                - name: data
                  value: '{{ `{{ inputs.parameters.interactions }}` }}'
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Release.Name }}-steps
  namespace: argo
spec:
  volumes:
    - name: schema-vol
      configMap:
        name: schema-cm
  templates:
    - name: transform-step
      inputs:
        parameters:
          - name: data
      container:
        image: '{{ .Values.workflow.image.repository }}:{{ .Values.workflow.image.tag }}'
        command: [ python ]
        args:
          - -m
          - mar.workflow.transform
          - --data
          - '{{`{{ inputs.parameters.data }}`}}'
          - --schema
          - /etc/schema/schema.yaml
        imagePullPolicy: IfNotPresent
        env:
          - name: QDRANT_URL
            value: >
              {{ .Values.qdrant.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local
          - name: QDRANT_PORT
            value: '6333'
        volumeMounts:
          - name: schema-vol
            mountPath: /etc/schema
