---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow
  namespace: argo
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: users
          - name: items
          - name: interactions
          - name: schema
      dag:
        tasks:
          - name: transform:users
            templateRef: &template
              name: workflow-tmpl
              template: step
            arguments:
              parameters:
                - name: step
                  value: transform
                - name: arguments
                  value: >- 
                    --data {{`{{ inputs.parameters.users }}`}}
                    --schema {{`{{ inputs.parameters.schema }}`}}
                    --target users
          - name: transform:items
            templateRef:
              <<: *template
            arguments:
              parameters:
                - name: step
                  value: transform
                - name: arguments
                  value: >- 
                    --data {{`{{ inputs.parameters.items }}`}}
                    --schema {{`{{ inputs.parameters.schema }}`}}
                    --target items
          - name: transform:interactions
            templateRef:
              <<: *template
            arguments:
              parameters:
                - name: step
                  value: transform
                - name: arguments
                  value: >- 
                    --data {{`{{ inputs.parameters.interactions }}`}}
                    --schema {{`{{ inputs.parameters.schema }}`}}
                    --target interactions
            dependencies: 
              - transform:users
              - transform:items
