---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Release.Name }}
  namespace: argo
spec:
  arguments: &workflow-arguments
    parameters:
      {{- range .Values.workflow.schema.datasets }}
      - name: {{ .name }}
      {{- end }}
  entrypoint: main
  templates:
    - name: main
      inputs:
        <<: *workflow-arguments
      dag:
        tasks:
          {{- range .Values.workflow.schema.datasets }}
          - name: transform-{{ .name }}
            templateRef:
              name: {{ $.Release.Name }}-steps
              template: transform-{{ .name }}-tpl
            arguments:
              parameters:
                - name: data
                  value: '{{ `{{ inputs.parameters` }}.{{ .name }} }}'
              {{- $hasReferences := false }}
              {{- range .features }}
                {{- if .references }}
                  {{- $hasReferences = true }}
                {{- end }}
              {{- end }}
              {{- if $hasReferences }}
              artifacts:
                {{- range .features }}
                {{- if .references }}
                - name: {{ .references.dataset }}
                  from: >
                    {{ `{{ steps.transform` }}-{{ .references.dataset }}.outputs.artifacts.transform }}
                {{- end }}
                {{- end }}
              {{- end }}
          {{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ $.Release.Name }}-steps
  namespace: argo
spec:
  volumes:
    - name: schema-vol
      configMap:
        name: schema-cm
  templates:
    {{- range .Values.workflow.schema.datasets }}
    - name: transform-{{ .name }}-tpl
      inputs:
        parameters:
          - name: data
        {{- $hasReferences := false }}
        {{- range .features }}
          {{- if .references }}
            {{- $hasReferences = true }}
          {{- end }}
        {{- end }}
        {{- if $hasReferences }}
        artifacts:
          {{- range .features }}
          {{- if .references }}
          - name: {{ .references.dataset }}
            path: /inputs/references/{{ .references.dataset }}/transform.pkl
          {{- end }}
          {{- end }}
        {{- end }}
      outputs:
        artifacts:
          - name: transformer
            path: /outputs/references/{{ .name }}/transform.pkl
      container:
        image: >-
          {{ $.Values.workflow.image.repository }}:{{ $.Values.workflow.image.tag }}
        command: [ python ]
        args:
          - -m
          - mar.workflow.transform
          - --data
          - '{{ `{{ inputs.parameters.data }}` }}'
          - --schema
          - /etc/schema/schema.yaml
        volumeMounts:
          - name: schema-vol
            mountPath: /etc/schema
    {{- end }}
