---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Release.Name }}
  namespace: argo
spec:
  arguments: &workflow-arguments
    parameters:
      - name: users
        default: ''
      - name: items
        default: ''
      - name: interactions
  entrypoint: main
  templates:
    - name: main
      inputs:
        <<: *workflow-arguments
      dag:
        tasks:
          {{- range $target := list "users" "items" }}
          - name: transform-{{ $target }}
            templateRef:
              name: {{ $.Release.Name }}-steps
              template: transform-step
            arguments:
              parameters:
                - name: data
                  value: '{{ printf "{{ inputs.parameters.%s }}" $target }}'
                - name: target
                  value: {{ $target }}
            when: >-
              {{ printf "{{ inputs.parameters.%s }}" $target }} != ''
          {{- end }}
          - name: transform-interactions
            templateRef:
              name: {{ .Release.Name }}-steps
              template: transform-step
            arguments:
              parameters:
                - name: data
                  value: '{{ `{{ inputs.parameters.interactions }}` }}'
            depends: >-
              (transform-users.Succeeded || transform-users.Omitted || transform-users.Skipped) ||
              (transform-items.Succeeded || transform-items.Omitted || transform-items.Skipped)
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Release.Name }}-steps
  namespace: argo
spec:
  templates:
    - name: transform-step
      inputs:
        parameters:
          - name: data
      container:
        image: '{{ .Values.workflow.image.repository }}:{{ .Values.workflow.image.tag }}'
        command: [ python ]
        args:
          - -m
          - mar.workflow.transform
          - --data
          - '{{`{{ inputs.parameters.data }}`}}'
          - --schema
          - '{{`{{ inputs.parameters.schema }}`}}'
        imagePullPolicy: IfNotPresent
        env:
          - name: QDRANT_URL
            value: >
              {{ .Values.qdrant.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local
          - name: QDRANT_PORT
            value: '6333'
